import { Button } from "std-widgets.slint";

export component LoginWindow inherits Window {
    width: 400px;
    height: 300px;

    // Define properties for username and password input
    property <string> username;
    property <string> user_password;
    in-out property <string> button_text: "Login";
    
    callback login_clicked(string, string);

    VerticalLayout {
        padding: 20px;
        spacing: 5px;

        // Login Title
        Text {
            text: "Discord Login";
            font-size: 24px;
            font-weight: 800;
        }

        Text {
            text: "Username/Email";
            font-size: 16px;
        }

        // Username Input
        Rectangle {
            width: parent.width * 0.8;
            height: 40px;
            border-radius: 10px;
            background: #ecf0f1;

            TextInput {
                text: "john.doe@email.com";
                color: gray;
                edited => {username = self.text}
                vertical-alignment: center;
                x: 10px;
                width: parent.width - 10px;
            }
        }

        Text {
            text: "Password";
            font-size: 16px;
        }

        // Password Input
        Rectangle {
            width: parent.width * 0.8;
            height: 40px;
            border-radius: 10px;
            background: #ecf0f1;

            TextInput {
                text: user_password;
                input-type: password;
                color: gray;
                edited => {user_password = self.text}
                vertical-alignment: center;
                x: 10px;
                width: parent.width - 10px;
            }
        }

        // Login Button
        Rectangle {
            width: 100px;
            height: 50px;
            background: #404468;
            border-radius: 10px;

            Button {
                text: button_text;
                width: parent.width;
                height: parent.height;
    
                clicked => {
                    login_clicked(username, user_password);
                }
            }
        }
        
    }
}
