import { Button } from "std-widgets.slint";

export component LoginWindow inherits Window {
    title: "Login";
    width: 400px;
    height: 300px;
    // Animate the x property for smooth sliding
    animate x { 
        duration: 300ms;
        easing: ease-in-out;
    }

    // Define properties for username and password input
    property <string> username;
    property <string> user_password;
    in property <bool> is_loading;
    
    callback login_clicked(string, string);

    VerticalLayout {
        padding: 20px;
        spacing: 5px;

        // Login Title
        Text {
            text: "Login";
            font-size: 24px;
        }

        // Username Input
        Rectangle {
            width: parent.width * 0.8;
            height: 40px;
            border-radius: 10px;
            background: #ecf0f1;

            TextInput {
                text: "Enter your username/email";
                color: gray;
                edited => {username = self.text}
            }
        }

        // Password Input
        Rectangle {
            width: parent.width * 0.8;
            height: 40px;
            border-radius: 10px;
            background: #ecf0f1;

            TextInput {
                text: user_password;
                input-type: password;
                color: gray;
                edited => {user_password = self.text}
            }
        }

        // Login Button
        Button {
            text: "Login";

            clicked => {
                login_clicked(username, user_password);
            }
        }
    }
}
