import { Button } from "std-widgets.slint";
import { LoginWindow } from "src/ui/login.slint";

export component MainWindow inherits Window {
    // Set minimum and maximum sizes of window
    min_width: 1024px;
    min_height: 576px;
    max_width: 1920px;
    max_height: 1080px;

    // Set the application icon and name
    title: "Lounge Lizard Multi-Chat";
    icon: @image-url("assets/loungelizard.png");

    in property <[string]> server_names;
    in property <[string]> server_ids;
    in property <[string]> server_channels_names;
    in property <[string]> server_channels_ids;
    in property <[string]> channel_messages;
    property <bool> show_login: false;
    property <string> chat_message;
    property <string> current_channel_id;
    property <length> login_screen_pos : 0px;
    property <float> login_opacity: 0.0;

    public function toggle_show_login() {
        show_login = !show_login;
        if (show_login) {
            login_screen_pos = 400px;
            login_opacity = 1.0;
        }
        else {
            login_screen_pos = 0px;
            login_opacity = 0.0;
        }
        
    }

    callback ServerButtonClicked(string);
    callback ServerChannelButtonClicked(string);
    callback process_login(string, string);
    callback send_message(string, string);

    Rectangle {
        width: 400px;
        x: parent.width - login_screen_pos;
        z: 1;
        background: orange;
        

        animate x {
            duration: 800ms;
            easing: ease-in-out;
        }

        // Animate the opacity for fade-in
        opacity: login_opacity;
        animate opacity { 
            duration: 700ms;
            easing: ease-in-out;
        }

        
        // if show_login : 
        LoginWindow{
            login_clicked(username, password) => {
                if (!show_login) {
                    self.is_loading = false;
                }
                process_login(username, password)
            }
        }
    }

    HorizontalLayout {
        // Sidebar
        VerticalLayout {
            width: 60px;
            height: parent.height;

            Rectangle {
                width: parent.width;
                height: parent.height;
                background: #182954;

                VerticalLayout {
                    width: parent.width;
                    height: parent.height;
                    padding-left: 5px;
                    padding-top: 5px;
                    spacing: 5px;

                    // First circle icon
                    Rectangle {
                        width: 50px;
                        height: 50px;
                        background: #ffa024;
                        border-radius: 25px;
                        Image {
                            source: @image-url("assets/discord_logo.png");
                            width: 70%;
                            height: 70%;
                        }
                        touch-area:= TouchArea {
                            width: parent.width;
                            height: parent.height;
                            clicked => {
                                toggle_show_login();
                            }
                        }
                        
                    }

                    // Second circle icon
                    Rectangle {
                        width: 50px;
                        height: 50px;
                        background: #ff6600;
                        border-radius: 25px;
                        Button {
                            
                        }
                        Image {
                            source: @image-url("assets/msteams_logo.png");
                            width: 70%;
                            height: 70%;
                        }
                    }

                    // Third circle icon
                    Rectangle {
                        width: 50px;
                        height: 50px;
                        background: #ffa024;
                        border-radius: 25px;
                        Image {
                            source: @image-url("assets/slack_logo.png");
                            width: 70%;
                            height: 70%;
                        }
                    }
                }
            }
        }

        // Content area with server names
        if !show_login: VerticalLayout {
            width: 20%;
            padding: 10px;
            spacing: 5px;

            // Display each server name in a text field
            for server_name[i] in server_names: Text {
                Rectangle {
                    background: #363e52;
                    Button {
                        property <string> server_id: server_ids[i];
                        text: server_name;

                        clicked => {
                            ServerButtonClicked(server_id)
                        }
                    }
                }
                    
            }
        }

        // Content area with server names
        if !show_login: VerticalLayout {
            width: 20%;
            padding: 10px;
            spacing: 5px;

            // Display each server name in a text field
            for server_channel_name[i] in server_channels_names: Text {
                Rectangle {
                    background: #363e52;
                    Button {
                        property <string> server_channel_id: server_channels_ids[i];
                        text: server_channel_name;

                        clicked => {
                            current_channel_id = server_channel_id;
                            ServerChannelButtonClicked(server_channel_id)
                        }
                    }
                }
                    
            }
        }

        if !show_login: VerticalLayout {
            padding: 10px;
            height: parent.height;
            spacing: 5px;

            Text {
                text: "Messages";
                color: white;
                font-size: 18px;
            }

            Flickable {
                height: parent.height - 150px;
            
                // The inner content that is scrollable
                VerticalLayout {
                    padding: 10px;
                    spacing: 5px;
            
                    // Iterate over the messages and display them
                    for channel_message[i] in channel_messages: Text {
                        Rectangle {
                            height: 20px;
                            background: #363e52;
            
                            Text {
                                text: channel_message;
                            }
                        }
                    }
                }
            }

             // Message input and send button section
             HorizontalLayout {
                height: 50px;
                spacing: 10px;

                // Text input for the message
                TextInput {
                    width: 80%;   // Adjust width for the input box
                    text: "Type your message...";
                    edited => {chat_message = self.text}
                }

                // Send button
                Button {
                    text: "Send";
                    clicked => {
                        // Trigger send message callback with input text
                        send_message(current_channel_id, chat_message);
                    }
                }
            }
        }
    }
}
